#!/usr/bin/env python3
import os
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pkg install python3 -y")
os.system("pkg install wordlist -y")
os.system("pkg install perl -y")
os.system("pkg install php -y")
os.system("pkg install pip -y")
os.system("pkg install pip2 -y")
os.system("pkg install vim -y")
os.system("pkg install cat -y")
os.system("pkg install nano -y")
os.system("pkg install nmap -y")
os.system("pkg install hydra -y")
os.system("pkg install openssl -y")
os.system("pkg install nodejs -y")
os.system("pkg install wget -y")
os.system("git clone https://github.com/Gameye98/Lazymux")
os.system("pkg install fakeroot -y")
os.system("git clone https://github.com/issamelferkh/userrecon")
os.system("git clone https://github.com/XCHADXFAQ77X/XERXES")
os.system("pkg install figlet -y")
os.system("pkg install cowsay -y")
os.system("clear")
os.system("figlet DarkSouL-S")
print("cowsay Completed")
